name: flutter_mapas_osm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^6.2.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  provider: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_map: ^8.1.1
  flutter_map_marker_popup: ^8.0.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
